const drinksData = [
    [
        { name: "Water", servingSize: "1 ml", calories: 0, sugar: 0, caffeine: 0 },
        { name: "Lemonade", servingSize: "1 ml", calories: 0.5, sugar: 0.118, caffeine: 0 },
        { name: "Pure Leaf Sweet Tea", servingSize: "1 ml", calories: 0.28, sugar: 0.076, caffeine: 0.16 },
        { name: "Arizona Sweet Tea", servingSize: "1 ml", calories: 0.34, sugar: 0.086, caffeine: 0.11 },
        { name: "Coffee (black)", servingSize: "1 ml", calories: 0.008, sugar: 0, caffeine: 0.41 },
        { name: "Herbal tea", servingSize: "1 ml", calories: 0, sugar: 0, caffeine: 0 },
        { name: "Hot chocolate (Swiss Miss)", servingSize: "1 ml", calories: 0.68, sugar: 0.12, caffeine: 0 },
        { name: "Milk (whole)", servingSize: "1 ml", calories: 0.63, sugar: 0.05, caffeine: 0 },
        { name: "Oat milk", servingSize: "1 ml", calories: 0.38, sugar: 0.02, caffeine: 0 },
        { name: "Coconut water", servingSize: "1 ml", calories: 0.19, sugar: 0.04, caffeine: 0 },
        { name: "Orange juice", servingSize: "1 ml", calories: 0.46, sugar: 0.09, caffeine: 0 },
        { name: "Apple juice", servingSize: "1 ml", calories: 0.61, sugar: 0.13, caffeine: 0 },
        { name: "Cranberry juice", servingSize: "1 ml", calories: 0.02, sugar: 0.004, caffeine: 0 },
        { name: "Fruit Smoothie", servingSize: "1 ml", calories: 0.57, sugar: 0.07, caffeine: 0 },
        { name: "Vanilla Milkshake (McDonald's)", servingSize: "1 ml", calories: 1.20, sugar: 0.13, caffeine: 0 },
        { name: "Chocolate Milkshake (McDonald's)", servingSize: "1 ml", calories: 1.37, sugar: 0.18, caffeine: 0 },
        { name: "Sparkling water", servingSize: "1 ml", calories: 0, sugar: 0, caffeine: 0 },
        { name: "Kombucha", servingSize: "1 ml", calories: 0.11, sugar: 0.03, caffeine: 0.05 },
        { name: "Shirley Temple", servingSize: "1 ml", calories: 0.79, sugar: 0.17, caffeine: 0 },
        { name: "Arnold Palmer", servingSize: "1 ml", calories: 0.37, sugar: 0.09, caffeine: 0.03 },
        { name: "Horchata", servingSize: "1 ml", calories: 0.52, sugar: 0.09, caffeine: 0 },
        { name: "Aguas frescas (Minute Maid)", servingSize: "1 ml", calories: 0.19, sugar: 0.05, caffeine: 0 },
        { name: "Chai latte", servingSize: "1 ml", calories: 0.50, sugar: 0.07, caffeine: 0.05 },
        { name: "Matcha latte", servingSize: "1 ml", calories: 0.50, sugar: 0.03, caffeine: 0.04 },
        { name: "Aloe vera juice", servingSize: "1 ml", calories: 0.15, sugar: 0.04, caffeine: 0 },
        { name: "Fruit punch", servingSize: "1 ml", calories: 0.45, sugar: 0.13, caffeine: 0 },
        { name: "Italian soda", servingSize: "1 ml", calories: 0.30, sugar: 0.08, caffeine: 0 },
        { name: "Sparkling apple cider", servingSize: "1 ml", calories: 0.59, sugar: 0.13, caffeine: 0 },
        { name: "Grape juice", servingSize: "1 ml", calories: 0.64, sugar: 0.15, caffeine: 0 },
        { name: "Pomegranate juice", servingSize: "1 ml", calories: 0.57, sugar: 0.13, caffeine: 0 },
        { name: "Coca-Cola", servingSize: "1 ml", calories: 0.44, sugar: 0.10, caffeine: 0.09 },
        { name: "Pepsi", servingSize: "1 ml", calories: 0.44, sugar: 0.10, caffeine: 0.09 },
        { name: "Sprite", servingSize: "1 ml", calories: 0.43, sugar: 0.11, caffeine: 0 },
        { name: "Mountain Dew", servingSize: "1 ml", calories: 0.49, sugar: 0.13, caffeine: 0.15 },
        { name: "Dr. Pepper", servingSize: "1 ml", calories: 0.42, sugar: 0.11, caffeine: 0.12 },
        { name: "7UP", servingSize: "1 ml", calories: 0.43, sugar: 0.11, caffeine: 0 },
        { name: "Fanta (orange)", servingSize: "1 ml", calories: 0.45, sugar: 0.12, caffeine: 0 },
        { name: "Mug Root Beer", servingSize: "1 ml", calories: 0.45, sugar: 0.12, caffeine: 0 },
        { name: "Ginger Ale", servingSize: "1 ml", calories: 0.39, sugar: 0.10, caffeine: 0 },
        { name: "Cream Soda", servingSize: "1 ml", calories: 0.48, sugar: 0.13, caffeine: 0 },
        { name: "Orange Crush", servingSize: "1 ml", calories: 0.45, sugar: 0.12, caffeine: 0 },
        { name: "A&W Root Beer", servingSize: "1 ml", calories: 0.43, sugar: 0.11, caffeine: 0 },
        { name: "Squirt", servingSize: "1 ml", calories: 0.42, sugar: 0.12, caffeine: 0 },
        { name: "Barq's Root Beer", servingSize: "1 ml", calories: 0.45, sugar: 0.12, caffeine: 0 },
        { name: "Canada Dry", servingSize: "1 ml", calories: 0.39, sugar: 0.10, caffeine: 0 },
        { name: "Sierra Mist", servingSize: "1 ml", calories: 0.39, sugar: 0.10, caffeine: 0 },
        { name: "Jones Soda", servingSize: "1 ml", calories: 0.45, sugar: 0.10, caffeine: 0 },
        { name: "Mexican Coke", servingSize: "1 ml", calories: 0.42, sugar: 0.11, caffeine: 0.10 },
        { name: "Blueberry Faygo", servingSize: "1 ml", calories: 0.42, sugar: 0.11, caffeine: 0 },
        { name: "Shasta", servingSize: "1 ml", calories: 0.37, sugar: 0.09, caffeine: 0.13 }
    ]
    
  
  ];
  export default drinksData;