import { StyleSheet } from "react-native";
import Constants from 'expo-constants';

const styles = StyleSheet.create({
    container: { // Wraps whole app
      flex: 1,
      backgroundColor: '#FAF9F6', // White background
      alignItems: 'center', // Center items horizontally
      justifyContent: 'space-between', // Evenly space items vertically
      paddingTop: 50, // Add padding to the top of the app
    },
    changefont:{ //Sets font of app
      fontFamily: 'Roboto',
      fontSize:30,
      fontWeight:'bold',
    },
    buttonContainer:{ //Wraps the + button
      width: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 76, // Adjust this value to move the button up or down on the page
    },
    roundButton: { // + button
      width: 70,
      height: 70,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 10,
      borderRadius: 40,
      backgroundColor: '#BF40BF',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.8,
      shadowRadius: 2,
      elevation: 5,
    },
    buttonText: { // + button text
      color: 'white',
      fontSize: 30, 
    },
    menuButton: { // Menu button
      position: 'absolute',
      top: 55, // Adjust this value to move the button up or down on the page
      left: 20,
      zIndex:1, // Adjust this value to move the button left or right on the page
    },
    menuText: { // Text for the menu button
      fontSize: 35,
      color: '#000',
    },
    sectionTitle: { // Title of the app
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'baseline',
    },
    sectionTitleTextBig: { // Title of the app
      fontSize: 30,
      fontWeight: 'bold',
      marginHorizontal: 5,
      textDecorationLine: 'underline',
    },
    sectionTitleTextSmallGoal: { // Title of the app
      fontSize: 20,
      fontWeight: 'bold',
      marginHorizontal: 5,
      left: 10,
      textDecorationLine: 'underline',
    },
    sectionTitleTextSmallDaily: { // Title of the app
      fontSize: 20,
      fontWeight: 'bold',
      marginHorizontal: 5,
      right: 10,
      textDecorationLine: 'underline',
    },
    totalTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      marginTop: 10,
    },
    DrinkWrapper: { // Wraps the drinks
      paddingTop: 5, // Add padding to the top of the app
      paddingHorizontal: 20, // Add padding to the left and right of the app
      width: '100%', // Make the wrapper take up the full width of the screen
      justifyContent: 'center',
      alignItems: 'center',
    },
    items: { // Wraps the drinks
      marginTop: 30, // Add margin to the top of the drinks
    },
    modalContainer: { // Wraps the drinks
      flex: 1,
      justifyContent: 'flex-end',
      alignItems: 'center',
      backgroundColor: 'rgba(0,0,0.5,0.5)',
    },
    addCloseView: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    addWrapper:{ // Adding drinks section
      width: 70,
      height: 50,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 5,
      borderRadius: 30,
      backgroundColor: '#BF40BF',
      marginBottom: 30,
      marginTop: 10,
      left: 0,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.8,
      shadowRadius: 2,
      elevation: 5,
    },
    addText:{
      color: 'white',
      fontSize: 16,
    },
    textInputView: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      flexWrap: 'wrap',
    },
    modalView:{
      backgroundColor: '#FFF5EE',
      padding: 20,
      borderTopLeftRadius: 50,
      borderTopRightRadius: 50,
      width: '106%',
      bottom: 0,
    },
    input:{
      paddingVertical: 15,
      paddingHorizontal: 10,
      borderRadius: 30,
      borderColor: '#C0C0C0',
      borderWidth: 1,
      width: 180,
      left: 4,
      backgroundColor: 'white',
      marginBottom: 46,
      bottom: 1,
    },
    menuContainer: {
      flex: 1,
      justifyContent: 'flex-start',
      alignItems: 'flex-start',
      backgroundColor: 'rgba(0,0,0.5,0.5)',
    },
    menuContent: {
      backgroundColor: 'lightgrey',
      padding: 10,
      borderTopRightRadius: 20,
      borderBottomRightRadius: 20,
      width: '41%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
    },
  underline: {
    textDecorationLine: 'underline',
  },
    backButton: {
      position: 'absolute',
      top: 1,
      left: 5,
      padding: 10,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    MenuItemes: {
       flex: 2,
       right: 5,
       top: 20,
    },
     MenuItemestext:{
      fontFamily: 'Roboto',
      fontSize:21,
     },
     inputMessage: {
      paddingVertical: 15,
      paddingHorizontal: 10,
      backgroundColor: '#FFF',
      borderRadius: 30,
      borderColor: '#C0C0C0',
      borderWidth: 2,
      width: 400,
      marginBottom: 1,
      marginTop: -1,
    },

    totalVolumeButton: {
      width: 250,
      height: 60,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 10,
      borderRadius: 40,
      marginTop: 15,
      backgroundColor: '#E0B0FF',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.8,
      shadowRadius: 2,
      elevation: 5,
    },
    volumeTitle: { // Title of the app
      fontSize: 20,
      fontWeight: 'bold',
    },
    volumeFooter: { // Title of the app
      fontSize: 15,
      fontStyle: 'italic',
      color: '#484848',
    },
    totalPopup: {
      flex: 1,
      alignItems: 'center',
      backgroundColor: 'rgba(0,0,0.5,0.5)',
    },
    totalPopupView: {
      backgroundColor: '#FAF9F6',
      padding: 20,
      borderRadius: 10,
      width: '90%',
      marginTop: 10,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      flexWrap: 'wrap',
      marginHorizontal: 100,
    },
    totalPopupText: {
      justifyContent: "center",
      paddingHorizontal: 15,
      minHeight: 100,
      fontSize: 25,
    },
    totalPopupClose: {
      justifyContent: "center",
      alignItems: "center",
      padding: 10,
      flexDirection: "row",
      width: 70,
      height: 70,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 10,
      borderRadius: 40,
      marginHorizontal: '38%',
      backgroundColor: '#C3B1E1',
      bottom: -10,
    },
    todaysGoalContainer: {
      fontSize: 20,
      fontWeight: 'bold',
      flexDirection: 'row',
    },
    swipeBox:{
      flex: 1,
      borderColor: '#3d3d5c',
      backgroundColor: '#FFF5EE',
      borderWidth: 1,
      height: 365, 
      marginHorizontal: 30,
      padding: 20,
      borderRadius: 20, 
    },
    suggestionsContainer: {
      backgroundColor: '#FFF5EE',

    },
   suggestionItem: {
    borderRadius: 10,
    top: -39,
    marginTop: 1,
    marginBottom: -8,
    bottom: 1,
   },
   inputDrinks:{
     paddingVertical: 16,
      paddingHorizontal: 11,
      borderRadius: 30,
      borderColor: '#C0C0C0',
      borderWidth: 1,
      width: 200,
      left: -9,
      backgroundColor: 'white',
      marginBottom: 46,
      bottom: 1,
   },
    goalsTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      textDecorationLine: 'underline',
      marginHorizontal: 5,
    },
    alignEclipse: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      flexWrap: 'wrap',
      marginTop: 80,
      marginBottom: 10,
    },
    alignEclipseNoGoal: {
      position: 'absolute',
      bottom: -264,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      flexWrap: 'wrap',
    },
    greyElipses: {
      width: 10,
        height: 10,
        borderRadius: 50,
        backgroundColor: 'lightgrey',
        marginHorizontal: 5,
    },
    blackElipses: {
      width: 10,
        height: 10,
        borderRadius: 50,
        backgroundColor: '#BF40BF',
        marginHorizontal: 5,
    },
    addGoalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    timeContainer: {
      alignItems: 'center',
      paddingTop: 20,
      paddingBottom: 10,
      borderRadius: 20,
      backgroundColor: '#E0B0FF',
      width: '80%',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.8,
      shadowRadius: 2,
      elevation: 5,
      margin: 10,
    },
    timeFooter: { // Title of the app
      marginTop: 15,
      fontSize: 15,
      fontStyle: 'italic',
      color: '#484848',
    },
    textTimeBubble: {
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#BF40BF',
      width: 50,
      height: 50,
      borderRadius: 25,
      marginHorizontal: 10,
    },
    timeText: {
      fontSize: 25,
      color: '#FFFFFF',
      textAlign: 'center',
    },
    timeAbrviation: {
      position: 'absolute',
      top: 50,
      fontSize: 13,
      fontStyle: 'italic',
      color: '#484848',
    },
    })
export default styles;